### ISSUE TITLE
大佬您好，能否修一下pcie的支持？

### ISSUE THREAD

**Issue by FiveHair** [xiaomeng9597/iStoreOS-rk3566-demo#1]
您好大佬，能否抽空修复一下minipcie？

**Comment by FiveHair** [comment]
我买了panther x2 研究了一个多星期。 由于linux底子太差根本没有什么头绪，只瞎改过dts，编译成dtb替换，但是没有用。
实在是没办法了。

**Comment by xiaomeng9597** [comment]
没法支持这个，这个仓库忘记删除了，你不应该反馈到这个仓库里面

**Comment by xiaomeng9597** [comment]
黑豹x2 minipcie线路魔改过，非标准的minipcie接口，支持也没用，用不了固态硬盘这些，所以没法支持，你应该关注的仓库是这个https://github.com/xiaomeng9597/Actions-iStoreOS-For-RK35XX

**Comment by xiaomeng9597** [comment]
这个演示仓库过几天删除

**Comment by FiveHair** [comment]
> 黑豹x2 minipcie线路魔改过，非标准的minipcie接口，支持也没用，用不了固态硬盘这些，所以没法支持，你应该关注的仓库是这个https://github.com/xiaomeng9597/Actions-iStoreOS-For-RK35XX

好的 谢谢
